import random
N = ''
COUNT = ''
DIC = {}
NUM_LOW = 1
NUM_HIGH = 42

def main():
# main fucntion.
# include menu of the game and call all the functions.
    global N
    print("Welcome to the Number Guessing Game!\nWritten by Chen Xi.")    
    choose = str(input("Menu:\n(I)nformation\n(V)iew High Scores\n(P)lay Game\n(S)et Game Limits\n(Q)uit\n"))
    while choose != "Q" and choose != "q":  # This the menu of the game.
        if choose == "I" or choose == "i":
            print("This is a simple number guessing game. When the game is played, the computer randomly generates a number between lower and upper bounds (inclusive). These default to 1 and 42, but the user can choose to change them to any valid numbers between 0 and a number greater than the lower bound. Each player is prompted to provide name to start playing. The number of attempts to correctly guess the secret number generated by the computer is recorded. When (Q)uit is selected, the program will display the list of players and their respective scores, sorted by score. It will also display the player with the lowest score.")
        elif choose == "V" or choose == "v":
            viewHighScores()

        elif choose == "P" or choose == "p":
            print("See if you can get a best score.")
            name = str(input("What is you name?\n"))
            for key in DIC.keys():
                if key == name:
                    name = str(input(name+", you have played your turn already!\nWhat is your name?\n"))
                else:
                    break

            while name =='':
                name = str(input("Hi,tell me your name, please\n"))
            playMenu(name)
            N = name
            DIC[N] = COUNT
        elif choose == "S" or choose == "s":
            settingGameLimits()
        else:
                print("Invalid menu choice.")
        choose = str(input("Menu:\n(I)nformation\n(V)iew High Scores\n(P)lay Game\n(S)et Game Limits\n(Q)uit\n"))
    if DIC == {}:  # Check whether there is a player played the game.
        print("No one played this game. Please try to play!")
    else:
        print("Farewell and thank you for playing!")
        viewHighScores()
        bestScore()


def playMenu(n):
# This function is used to implement the main game play. The randint generate a random number, then compared with the number that user input to guess.
# While input, the function will have a error check whether the input is a number or a alphabet, then check whether the number is valid or not. By using the 'while' and isdigit().
# Use global to let other function can call the value of guessed times, which will be stored in global DICTIONARY.     
    global COUNT
    count = 1      # Count user's guessed times. 
    num = str(input(n+", please enter you guess, between "+str(NUM_LOW)+" and "+str(NUM_HIGH)+":\n"))
    num_guess = random.randint(NUM_LOW,NUM_HIGH)
    while not num.isdigit():   # Check the input is a number or alphabet.
        print("Invalid guess.")
        num = str(input(n+", please enter you guess, between "+str(NUM_LOW)+" and "+str(NUM_HIGH)+":\n"))
    
    while int(num) !=num_guess:    # Compare the input number with the random generated number that need to be guessed.
        while int(num) > NUM_HIGH or int(num) < NUM_LOW or num == '':   # Check the input number is valid or not.
            print("Invalid guess.")            
            num = str(input(n+", please enter you guess, between "+str(NUM_LOW)+" and "+str(NUM_HIGH)+":\n"))
            continue       
        if int(num) > num_guess:
            print("Your guess is too high!")
        else:
            print("Your guess is low!")
        count = count + 1
        num = str(input(n+", please enter you guess, between "+str(NUM_LOW)+" and "+str(NUM_HIGH)+":\n"))
    COUNT = count
    print("You got it!\nWell done, "+n+". You guessed it in "+str(count)+" guesses.")
    return num  #Return number to main function.
def settingGameLimits():
# This function is used to set the lower and upper bound.
# Global the lower and upper bound that other function can call these two values.
# Also the fucntion will have a error check whether the input lower and upper bound is valid.
    global NUM_LOW
    global NUM_HIGH
    num_low = str(input("Please enter a valid low bound integer:\n"))
    while not num_low.isdigit():  # Check the input is a number or alphabet.
        num_low = str(input("Please enter a valid low bound integer:\n"))
    while int(num_low) < 0:   # Check the input number is valid or not.
        num_low = str(input("Please enter a valid low bound integer:\n"))            
    print("Low bound is "+num_low)
    num_high = str(input("Please enter a valid high integer greater than "+str(num_low)+":\n"))
    while not num_high.isdigit():
        num_high = str(input("Please enter a valid high integer greater than "+str(num_low)+":\n"))
    while int(num_high) <= int(num_low):
        num_high = str(input("Please enter a valid high integer greater than "+str(num_low)+":\n"))     
    print("High bound is "+num_high)
    NUM_LOW = int(num_low)
    NUM_HIGH = int(num_high)
def viewHighScores():
# This function is used to show the score of each player.
# The the guessed times and the names of players will be stored in the global DICTIONARY.
# Using loop to print all the players' names and their scores(guessed times).        
    print("Score:")    
    for k,v in DIC.items():
        print("{0:10}{1:10d}".format(k,v))
def bestScore():
# This fucntion is used to show the players with high score that guessed the number by using minimum number of times.
# Using loop to check the values of dictionary which is minimum and print the key of the minimum values. Key is player name, value is score(guessed times). 
    print("Player(s) with best score is(are):")
    for key_2,value_2 in DIC.items():
        if value_2 == min(DIC.values()):
            print("{0:10}{1:10d}".format(key_2,value_2))    
    
main()